[project]
name = "agrinow"
version = "0.1.0"
description = "FastAPI on Cloudflare"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi",
    "sqlalchemy",
    "sqlalchemy-cloudflare-d1",
    "cryptography",
    "PyJWT",
    "httpx",
    "jinja2",
    "python-dotenv",
]

[dependency-groups]
dev = [
    "workers-py",
]

[tool.uv]
managed = true
