name: 🐍 API Dev Deploy
on:
  push:
    branches: [ do_not_touch ] # Change this to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 📂 Upload Files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_PY_DEV }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: ./
          server-dir: ./
