name: FTP Deployment

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch
  workflow_dispatch: # Allow manually triggering the workflow

jobs:
  web-deploy:
    name: 🎉 Deploy to FTP Site
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: 📂 Sync files (FTP Deploy)
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ./ 
        dangerous-clean-slate: true
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          .env*
          README.md
